### ISSUE TITLE
[Feature] Swap instructions and camera display

### ISSUE THREAD

**Issue by Citillara** [prof18/Secure-QR-Reader#2]
Hello,

I would like to ask if it would be possible for you to swap the instructions and the camera display. Most phones have their cameras on top of the phone. Here looking at the bottom of the screen while trying to aim at the QR Code makes it a bit akward.

Best regards,

**Comment by prof18** [comment]
Sorry, I didn't receive a notification! Anyway, in the new update, I've redesigned the scanner!


<img width="363" src="https://raw.githubusercontent.com/prof18/Secure-QR-Reader/master/store_assets/frame/raw/eng/Screenshot_20230519-221106.jpg">
